development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DPLA_ET_DEV_DB_NAME'] %>
  username: <%= ENV['DPLA_DEV_USERNAME'] %>
  password: <%= ENV['DPLA_DEV_PASSWORD'] %>
  pool: 100
  port: <%= ENV['DPLA_DEV_PORT'] %>
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_ET_DB_NAME'] %>
  username: <%= ENV['RDS_ET_USERNAME'] %>
  password: <%= ENV['RDS_ET_PASSWORD'] %>
  pool: 100
  port: <%= ENV['RDS_ET_PORT'] %>
  host: <%= ENV['RDS_ET_HOSTNAME'] %>


test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 100
  timeout: 5000
