development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DPLA_DEV_DB_NAME'] %>
  username: <%= ENV['DPLA_DEV_USERNAME'] %>
  password: <%= ENV['DPLA_DEV_PASSWORD'] %>
  pool: 5
  port: <%= ENV['DPLA_DEV_PORT'] %>
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  pool: 5
  port: <%= ENV['RDS_PORT'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>


test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
